name: Run AutoTests
on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: select tests to run
        required: true
        type: choice
        default: all
        options:
          - all
jobs:
  run-test:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Copy source code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5  
      - name: install dependencies
        run: pip install -r requirements.txt  
      - name: Run tests
        run: pytest -v -s 
       
        
       
